input CLOCK,
output LED_G,
output LED_R,
output LED_B,
output LCD_VSYNC,
output LCD_HSYNC,
output LCD_CS,
output LCD_CLK,
output LCD_ENABLE,
output LCD_BACKLIGHT_CTRL,
output UART_TX,
input UART_RX,
output I2C_SCL,
inout I2C_SDA,
input TRACKBALL_INTERRUPT,
input KEYPAD_INTERRUPT,
output I2S_SDOUT,
output I2S_SCLK,
output I2S_LRCK,
output I2S_MCLK,
inout SD_EXTERNAL_DAT1,
inout SD_EXTERNAL_DAT0,
output SD_EXTERNAL_CLK,
inout SD_EXTERNAL_CMD,
inout SD_EXTERNAL_DAT3,
inout SD_EXTERNAL_DAT2,
input SD_EXTERNAL_CARD,
input USB_HCI_INT,
output USB_HCI_MOSI,
input USB_HCI_MISO,
output USB_HCI_SS_n,
output USB_HCI_SCLK,
output USB_HCI_RESET_n,
output SRAM_WE,
output SRAM_OE,
output SDRAM_CLK,
output SDRAM_CKE,
output SDRAM_RAS_n,
output SDRAM_CAS_n,
output SDRAM_WE_n,
output SDRAM_CE_n,
output FLASH_nCS,
output FLASH_MOSI,
input FLASH_MISO,
inout FLASH_IO2,
inout FLASH_IO3,
inout [15:0] SDRAM_DQ,
output [1:0] SDRAM_BA,
output [12:0] SDRAM_A,
output [5:0] LCD_G,
output [5:0] LCD_B,
output [1:0] SDRAM_DQM,
output [5:0] LCD_R,
output [19:0] SRAM_A,
inout [15:0] SRAM_D
