input wire CLOCK,
output wire LED_G,
output wire LED_R,
output wire LED_B,
output wire LCD_VSYNC,
output wire LCD_HSYNC,
output wire LCD_CS,
output wire LCD_CLK,
output wire LCD_ENABLE,
output wire LCD_BACKLIGHT_CTRL,
output wire UART_TX,
input wire UART_RX,
inout wire I2C_SCL,
inout wire I2C_SDA,
input wire TRACKBALL_INTERRUPT,
input wire KEYPAD_INTERRUPT,
output wire I2S_SDOUT,
output wire I2S_SCLK,
output wire I2S_LRCK,
output wire I2S_MCLK,
output wire SD_EXTERNAL_CLK,
inout wire SD_EXTERNAL_CMD,
input wire SD_EXTERNAL_CARD,
input wire USB_HCI_INT,
output wire USB_HCI_MOSI,
input wire USB_HCI_MISO,
output wire USB_HCI_SS_n,
output wire USB_HCI_SCLK,
output wire USB_HCI_RESET_n,
output wire SRAM_WE,
output wire SRAM_OE,
output wire SRAM_BLE,
output wire SRAM_BHE,
output wire SDRAM_CLK,
output wire SDRAM_CKE,
output wire SDRAM_RAS_n,
output wire SDRAM_CAS_n,
output wire SDRAM_WE_n,
output wire SDRAM_CE_n,
output wire FLASH_nCS,
output wire FLASH_MOSI,
input wire FLASH_MISO,
inout wire FLASH_IO2,
inout wire FLASH_IO3,
output wire DEBUG_0,
output wire DEBUG_1,
output wire DEBUG_2,
output wire DEBUG_3,
output wire DEBUG_4,
output wire [5:0] LCD_B,
output wire [5:0] LCD_G,
output wire [5:0] LCD_R,
output wire [12:0] SDRAM_A,
output wire [1:0] SDRAM_BA,
inout wire [15:0] SDRAM_DQ,
output wire [1:0] SDRAM_DQM,
inout wire [3:0] SD_EXTERNAL_DAT,
output wire [19:0] SRAM_A,
inout wire [15:0] SRAM_D
