--[[
 RetroDÄCK
 Copyright (c) 2025 Anders Pistol.

 This Source Code Form is subject to the terms of the Mozilla Public
 License, v. 2.0. If a copy of the MPL was not distributed with this
 file, You can obtain one at https://mozilla.org/MPL/2.0/.
]]

import(traktor)
import(traktor.run)

run:loadScript("../klara-rv/sv2v.run")

local PATH_SOC < const > = "rtl"
local PATH_PERIFHERIALS < const > = "../klara-rv/rtl"

local SOURCE < const > =
{
	PATH_SOC .. "/RetroDACK.sv",
	-- PATH_SOC .. "/RetroDACK_VGA.sv",
	-- PATH_SOC .. "/RetroDACK_SRAM.sv",
	-- Library
	PATH_PERIFHERIALS .. "/audio/AUDIO_controller.sv",
	PATH_PERIFHERIALS .. "/audio/AUDIO_i2s_output.sv",
	PATH_PERIFHERIALS .. "/block/BRAM.sv",
	PATH_PERIFHERIALS .. "/block/BRAM_1r1w.sv",
	PATH_PERIFHERIALS .. "/clock/PLL_ECP5.sv",
	PATH_PERIFHERIALS .. "/fifo/FIFO.sv",
	PATH_PERIFHERIALS .. "/fifo/FIFO_BRAM.sv",
	PATH_PERIFHERIALS .. "/flash/SPI_Flash.sv",
	PATH_PERIFHERIALS .. "/misc/Bridge.sv",
	PATH_PERIFHERIALS .. "/misc/ClockDivider.sv",
	PATH_PERIFHERIALS .. "/misc/DualPort.sv",
	PATH_PERIFHERIALS .. "/misc/Reset.sv",
	PATH_PERIFHERIALS .. "/misc/Timer.sv",
	PATH_PERIFHERIALS .. "/misc/WriteBuffer.sv",
	PATH_PERIFHERIALS .. "/sdcard/SD.sv",
	PATH_PERIFHERIALS .. "/sdram/SDRAM_controller.sv",
	PATH_PERIFHERIALS .. "/sram/SRAM_controller.sv",
	PATH_PERIFHERIALS .. "/uart/UART.sv",
	PATH_PERIFHERIALS .. "/uart/UART_RX.sv",
	PATH_PERIFHERIALS .. "/uart/UART_TX.sv",
	PATH_PERIFHERIALS .. "/video/VIDEO_controller.sv",
	PATH_PERIFHERIALS .. "/video/VIDEO_VGA.sv",
	PATH_PERIFHERIALS .. "/i2c/I2C.sv",
	PATH_PERIFHERIALS .. "/cpu/CPU.sv",
	PATH_PERIFHERIALS .. "/cpu/CPU_BusMux.sv",
	PATH_PERIFHERIALS .. "/cpu/CPU_PLIC.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_ALU.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_BRAM.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_BRAM_1r1w.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_CSR.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_DCache_Comb.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_DCache_None.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_DCache_Reg.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_DCache_WB.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Decode.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Defines.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Divide.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Execute.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Fetch.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Forward.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_ICache_Comb.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_ICache_None.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_ICache_Reg.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Memory.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Multiply.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_PreDecode.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Registers.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_SkidBuffer.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Types.sv",
	PATH_PERIFHERIALS .. "/cpu/private/CPU_Writeback.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_Add.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_Compare.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_Div.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_Float.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_Int.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_Mul.sv",
	PATH_PERIFHERIALS .. "/cpu/private/fpu/CPU_FPU_MulAdd.sv"
}

local function writeFile(fn, lines)
	local f = fileSystem:open(Path(run.cwd .. "/" .. fn), File.FmWrite)
	if f == nil then return false end
	local so = StreamOutput(f, Utf8Encoding())
	for _, ln in ipairs(lines) do
		so:printLn(ln)
	end
	f:close()
end

local function buildRV()
	local TRAKTOR_HOME < const > = os:getEnvironment("TRAKTOR_HOME")
	local SCRIPT_HOME < const > = fileSystem:getAbsolutePath(Path(os:getEnvironment("RUN_SCRIPT_PATH"))):normalized().pathNameOS

	os:setEnvironment("MAKE_OS", "linux")
	os:setEnvironment("MAKE_DIALECT", "make")
	os:setEnvironment("MAKE_FORMAT", TRAKTOR_HOME .. "/resources/build/configurations/make-format.sbm")
	os:setEnvironment("MAKE_INCLUDE", SCRIPT_HOME .. "/../klara-rv/make-config-rv32imf_zicsr.inc")
	os:setEnvironment("MAKE_TOOLCHAIN", "gcc")
	os:setEnvironment("MAKE_OBJECT_FILE", "%s.o")
	os:setEnvironment("MAKE_STATIC_LIBRARY_FILE", "lib%s.a")
	os:setEnvironment("MAKE_SHARED_LIBRARY_FILE", "lib%s.so")
	os:setEnvironment("MAKE_EXECUTABLE_FILE", "%s")
	os:setEnvironment("MAKE_VERBOSE", "false")
	os:setEnvironment("MAKE_HOME", SCRIPT_HOME)

	run:execute(
		TRAKTOR_HOME .. "/bin/linux/releasestatic/Traktor.SolutionBuilder.App " ..
		"-f=make2 " ..
		"-make-solution-template=" .. TRAKTOR_HOME .. "/resources/build/configurations/make-solution.sbm " ..
		"-make-project-template=" .. TRAKTOR_HOME .. "/resources/build/configurations/make-project.sbm " ..
		"retrodack-rv.xms"
	)

	run:pushd("build/rv")
	if run:execute("make -f RetroDACK.mak ReleaseStatic") ~= 0 then return false end
	run:popd()

	-- Create binary and dump files of firmware.
	run:execute("riscv32-unknown-elf-objcopy -O binary build/rv/ReleaseStatic/Firmware build/rv/ReleaseStatic/Firmware.bin")
	run:execute("riscv32-unknown-elf-objdump -D build/rv/ReleaseStatic/Firmware", "build/rv/ReleaseStatic/Firmware.dump")

	-- Create dump files of dashboard.
	run:execute("riscv32-unknown-elf-objdump -D build/rv/ReleaseStatic/Dashboard", "build/rv/ReleaseStatic/Dashboard.dump")
	run:execute("riscv32-unknown-elf-objdump -D build/rv/ReleaseStatic/Doom", "build/rv/ReleaseStatic/Doom.dump")
	run:execute("riscv32-unknown-elf-objdump -D build/rv/ReleaseStatic/ScummRV", "build/rv/ReleaseStatic/ScummRV.dump")

	return true
end

local function buildHostLinux()
	local TRAKTOR_HOME < const > = os:getEnvironment("TRAKTOR_HOME")

	os:setEnvironment("MAKE_OS", "linux")
	os:setEnvironment("MAKE_DIALECT", "make")
	os:setEnvironment("MAKE_FORMAT", TRAKTOR_HOME .. "/resources/build/configurations/make-format.sbm")
	os:setEnvironment("MAKE_INCLUDE", TRAKTOR_HOME .. "/resources/build/configurations/make-config-linux.inc")
	os:setEnvironment("MAKE_TOOLCHAIN", "gcc")
	os:setEnvironment("MAKE_OBJECT_FILE", "%s.o")
	os:setEnvironment("MAKE_STATIC_LIBRARY_FILE", "lib%s.a")
	os:setEnvironment("MAKE_SHARED_LIBRARY_FILE", "lib%s.so")
	os:setEnvironment("MAKE_EXECUTABLE_FILE", "%s")
	os:setEnvironment("MAKE_VERBOSE", "false")

	run:execute(
		TRAKTOR_HOME .. "/bin/linux/releasestatic/Traktor.SolutionBuilder.App " ..
		"-f=make2 " ..
		"-make-solution-template=" .. TRAKTOR_HOME .. "/resources/build/configurations/make-solution.sbm " ..
		"-make-project-template=" .. TRAKTOR_HOME .. "/resources/build/configurations/make-project.sbm " ..
		"retrodack-linux.xms"
	)

	run:pushd("build/linux")
	if run:execute("make -f RetroDACK.mak ReleaseStatic") ~= 0 then return false end
	run:popd()

	return true
end

local function buildHostWin64()
	local TRAKTOR_HOME < const > = os:getEnvironment("TRAKTOR_HOME")

	if run:execute(
		TRAKTOR_HOME .. "/bin/win64/releasestatic/Traktor.SolutionBuilder.App " ..
		"-f=msvc " ..
		"-p=" .. TRAKTOR_HOME .. "/resources/build/configurations/msvc-2022-win64.xml " ..
		"retrodack-win64.xms"
	) ~= 0 then
		stderr:printLn("Failed to execute solution generator.")
		return false
	end

	run:pushd("build/win64")

	writeFile(
		"build.bat",
		{
			"@echo off",
			"call \"" .. TRAKTOR_HOME .. "/scripts/config.bat\"",
			"call \"" .. TRAKTOR_HOME .. "/scripts/config-vs-x64.bat\"",
			"msbuild -m RetroDACK.sln /p:Configuration=ReleaseStatic"
		}
	)

	if run:execute("build/win64/build.bat") ~= 0 then
		stderr:printLn("Failed to execute build file.")
		return false
	end

	run:popd()

	return true
end

local function buildEmulatorFS()
	local SCRIPT_HOME < const > = fileSystem:getAbsolutePath(Path(os:getEnvironment("RUN_SCRIPT_PATH"))):normalized().pathNameOS

	run:mkdir(SCRIPT_HOME .. "/fs")
	run:rm(SCRIPT_HOME .. "/fs/*.*")
	run:replace(SCRIPT_HOME .. "/build/rv/ReleaseStatic/Dashboard", SCRIPT_HOME .. "/fs/dash")
	run:replace(SCRIPT_HOME .. "/build/rv/ReleaseStatic/Doom", SCRIPT_HOME .. "/fs/doom")
	run:replace(SCRIPT_HOME .. "/code/Doom/doom1.wad", SCRIPT_HOME .. "/fs/doom1.wad")
	run:replace(SCRIPT_HOME .. "/code/Doom/doom2.wad", SCRIPT_HOME .. "/fs/doom2.wad")
	run:replace(SCRIPT_HOME .. "/build/rv/ReleaseStatic/ScummRV", SCRIPT_HOME .. "/fs/scummrv")
	run:replace(SCRIPT_HOME .. "/3rdp/pocketmod/songs/elysium.mod", SCRIPT_HOME .. "/fs/song.mod")

	-- Convert splash screen into RAW image.
	--[[
		local img = drawing.Image.loadFromFile(SCRIPT_HOME .. "/docs/Splash8.png")
		if img == nil then
			stderr:printLn("Unable to load image.")
			return 1
		end

		img:apply(drawing.ScaleFilter(720, 720))
		stdout:printLn("Image loaded; " .. img.width .. " * " .. img.height)

		local um = {}
		for y = 0, img.height - 1 do
			for x = 0, img.width - 1 do
				local clr = img:getPixel(x, y)
				local r = math.floor(clr.red * 255)
				local g = math.floor(clr.green * 255)
				local b = math.floor(clr.blue * 255)
				local c = (r << 16) | (g << 8) | b
				um[c] = true
			end
		end

		-- Counter number of unique colors.
		local unique = 0
		for c, _ in pairs(um) do
			unique = unique + 1
		end
		stdout:printLn(unique .. " unique colors")

		-- Create complete color palette.
		local plt = drawing.Palette(unique)
		local index = 0
		for c, _ in pairs(um) do
			local r = (c >> 16) / 255.0
			local g = ((c >> 8) & 255) / 255.0
			local b = (c & 255) / 255.0
			plt:set(index, Color4f(r, g, b, 1))
			index = index + 1
		end

		-- Reduce palette into 256 colors.
		stdout:printLn("Reducing palette...")
		plt = plt:reduce(256)

		-- Convert source image into palettized image.
		stdout:printLn("Converting...")
		img:convert(drawing.PixelFormat.getP8(), plt)

		-- Save a raw image prepended with palette.
		stdout:printLn("Saving raw...")
		local f = fileSystem:open(Path(SCRIPT_HOME .. "/fs/splash"), File.FmWrite)
		local bw = BitWriter(f)
		for i = 0, 255 do
			local clr = plt:get(i)
			local r = math.floor(clr.red * 255)
			local g = math.floor(clr.green * 255)
			local b = math.floor(clr.blue * 255)
			local c = (r << 16) | (g << 8) | b
			bw:writeUInt32(c)
		end
		StreamCopy(f, MemoryStream(img.data, img.dataSize)):execute()
		f:close()
	]]

	return true
end

function main()
	local compile < const > = run.commandLine:hasOption("compile")
	local synthesize < const > = run.commandLine:hasOption("synth")
	local flash < const > = run.commandLine:hasOption("flash")
	local program < const > = run.commandLine:hasOption("prog") or flash
	local emulation < const > = run.commandLine:hasOption("emu")
	local launch < const > = run.commandLine:hasOption("launch")

	local rtl < const > = "RetroDACK"
	-- local rtl < const > = "RetroDACK_VGA"
	-- local rtl < const > = "RetroDACK_SRAM"
	local flash_fw < const > = true

	-- Compile firmware and tools.
	if compile then
		if os.identifier == "windows" then
			if not buildHostWin64() then return 1 end
		else
			if not buildRV() then return 1 end
			if not buildHostLinux() then return 1 end
		end

		-- Build filesystem folder for emulator.
		if not buildEmulatorFS() then return 1 end
	end

	-- Synthesize system.
	if synthesize then

		-- Create constraints.
		stdout:printLn("==============================")
		stdout:printLn("Generating constraints...")
		stdout:printLn("==============================")
		run:run("./generate-constraints.run", "rtl/Constraints.lpf")
		run:run("./generate-top-io.run", "rtl/RetroDACK_IO.sv")

		-- Convert all source files into Verilog.
		stdout:printLn("==============================")
		stdout:printLn("Generating verilog...")
		stdout:printLn("==============================")
		local f = ""
		for _, sv in ipairs(SOURCE) do
			local v = sv2v(
				sv,
				{ ".", "./rtl", PATH_PERIFHERIALS .. "/cpu" },
				{},
				"build/rtl-v"
			)
			if v == nil then return 1 end
			f = f .. " " .. v
		end
		stdout:printLn(f)

		-- Ensure old bit file is removed.
		run:rm("build/" .. rtl .. ".bit")
		run:rm("build/" .. rtl .. ".json")
		run:rm("build/" .. rtl .. ".log")

		-- Synthesize
		stdout:printLn("==============================")
		stdout:printLn("Synthesize...")
		stdout:printLn("==============================")
		local tmr = Timer()
		local xc = run:execute("yosys -l build/" .. rtl .. ".log -p \"opt; share -aggressive; synth_ecp5 -abc9 -json build/" .. rtl .. ".json\" " .. f)
		-- local xc = run:execute(
		-- 	"yosys -l build/" .. rtl .. ".log " ..
		-- 	"-p \"" ..
		-- 		"read_verilog -noautowire " .. f .. "; " ..
		-- 		"opt; "..
		-- 		"share -aggressive; " ..
		-- 		"synth_ecp5 -abc9 -json build/" .. rtl .. ".json; " ..
		-- 	"\""
		-- )
		if xc ~= 0 then
			stderr:printLn("yosys failed; build aborted.")
			return 1
		end
		local duration_yosys = tmr.elapsedTime

		-- Place and route.
		stdout:printLn("==============================")
		stdout:printLn("Place and route...")
		stdout:printLn("==============================")
		local tmr = Timer()
		local xc = run:execute("nextpnr-ecp5 --25k --package CABGA256 --speed 6 --timing-allow-fail --top " .. rtl .. " --json build/" .. rtl .. ".json --textcfg build/" .. rtl .. ".config --lpf rtl/Constraints.lpf --report build/" .. rtl .. ".report.json --freq 100")
		if xc ~= 0 then
			stderr:printLn("nextpnr-ecp5 failed; build aborted.")
			return 1
		end
		local duration_nextpnr = tmr.elapsedTime

		-- Create bit file.
		stdout:printLn("==============================")
		stdout:printLn("Generating bit file...")
		stdout:printLn("==============================")
		local xc = run:execute("ecppack --compress --svf build/" .. rtl .. ".svf build/" .. rtl .. ".config build/" .. rtl .. ".bit")
		if xc ~= 0 then
			stderr:printLn("ecppack failed; build aborted.")
			return 1
		end
	
		stdout:printLn("yosys duration " .. string.format("%.2f", duration_yosys) .. " seconds.")
		stdout:printLn("nextpnr-ecp5 duration " .. string.format("%.2f", duration_nextpnr) .. " seconds.")
	end

	-- Program target.
	if program then
		local xc = 0

		-- Write firmware binary to target flash; this is executed in place thus need to be a flat binary.
		if flash_fw then
			stdout:printLn("==============================")
			stdout:printLn("Flashing firmware...")
			stdout:printLn("==============================")
			local offset < const > = 0x100000
			xc = run:execute("openFPGALoader -c cmsisdap -f --vid=0x1d50 --pid=0x602b --skip-reset -o " .. string.format("0x%08x", offset) .. " ./build/rv/ReleaseStatic/Firmware.bin")
			if xc ~= 0 then
				stderr:printLn("openFPGALoader failed to write firmware to SPI flash; build aborted.")
				return 1
			end
		end

		-- Write FPGA bitstream, either to SRAM or to target flash.
		if flash then
			stdout:printLn("==============================")
			stdout:printLn("Flashing bit file...")
			stdout:printLn("==============================")
			xc = run:execute("openFPGALoader -c cmsisdap -f --vid=0x1d50 --pid=0x602b ./build/" .. rtl .. ".bit")
		else
			stdout:printLn("==============================")
			stdout:printLn("Uploading bit file to SRAM...")
			stdout:printLn("==============================")
			xc = run:execute("openFPGALoader -c cmsisdap --vid=0x1d50 --pid=0x602b ./build/" .. rtl .. ".bit")
		end
		if xc ~= 0 then
			stderr:printLn("openFPGALoader failed to write bitstream to target; build aborted.")
			return 1
		end
	end

	-- Launch on target.
	if launch then
		run:execute("build/linux/ReleaseStatic/RetroDACK.Launch -elf=build/rv/ReleaseStatic/Dashboard")
	end

	-- Launch in emulator.
	if emulation then
		run:execute("build/linux/ReleaseStatic/RetroDACK.Emulator -elf=build/rv/ReleaseStatic/Dashboard")
	end

	stdout:printLn("Build successful.")
	return 0
end
