import(traktor)

function main()

	local img = drawing.Image.loadFromFile("docs/Splash.png")
	if img == nil then
		stderr:printLn("Unable to load image.")
		return 1
	end

	img:apply(drawing.ScaleFilter(720, 720))
	stdout:printLn("Image loaded; " .. img.width .. " * " .. img.height)

	local um = {}
	for y = 0, img.height - 1 do
		for x = 0, img.width - 1 do
			local clr = img:getPixel(x, y)
			local r = math.floor(clr.red * 255)
			local g = math.floor(clr.green * 255)
			local b = math.floor(clr.blue * 255)
			local c = (r << 16) | (g << 8) | b
			um[c] = true
		end
	end

	-- Counter number of unique colors.
	local unique = 0
	for c, _ in pairs(um) do
		unique = unique + 1
	end
	stdout:printLn(unique .. " unique colors")

	-- Create complete color palette.
	local plt = drawing.Palette(unique)
	local index = 0
	for c, _ in pairs(um) do
		local r = (c >> 16) / 255.0
		local g = ((c >> 8) & 255) / 255.0
		local b = (c & 255) / 255.0
		plt:set(index, Color4f(r, g, b, 1))
		index = index + 1
	end

	-- Reduce palette into 256 colors.
	stdout:printLn("Reducing palette...")
	plt = plt:reduce(256)

	-- Convert source image into palettized image.
	stdout:printLn("Converting...")
	img:convert(drawing.PixelFormat.getP8(), plt)

	-- Save a raw image prepended with palette.
	stdout:printLn("Saving raw...")
	local f = fileSystem:open(Path("Splash.rd"), File.FmWrite)
	local bw = BitWriter(f)
	for i = 0, 255 do
		local clr = plt:get(i)
		local r = math.floor(clr.red * 255)
		local g = math.floor(clr.green * 255)
		local b = math.floor(clr.blue * 255)
		local c = (b << 24) | (g << 16) | (r << 8) | 0
		bw:writeUInt32(c)
	end
	StreamCopy(f, MemoryStream(img.data, img.dataSize)):execute()
	f:close()

	-- Save preview.
	stdout:printLn("Saving preview...")
	img:convert(drawing.PixelFormat.getR8G8B8())
	img:save("Splash.png")

end
